  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::dubhe_asset_account {

  use sui::bcs::{to_bytes};

  use dubhe::table_id;

  use dubhe::dapp_state;

  use dubhe::dapp_service;

  use dubhe::dapp_hub;

  use dubhe::dapp_hub::DappHub;

  use dubhe::dubhe_dapp_key;

  use dubhe::dubhe_dapp_key::DappKey;

  use dubhe::dubhe_account_status;

  use dubhe::dubhe_account_status::{AccountStatus};

  const TABLE_NAME: vector<u8> = b"asset_account";

  public struct Asset_account has copy, drop, store {
    balance: u256,
    status: AccountStatus,
  }

  public fun new(balance: u256, status: AccountStatus): Asset_account {
    Asset_account {
            balance,
            status,
        }
  }

  public fun balance(self: &Asset_account): u256 {
    self.balance
  }

  public fun status(self: &Asset_account): AccountStatus {
    self.status
  }

  public fun update_balance(self: &mut Asset_account, balance: u256) {
    self.balance = balance
  }

  public fun update_status(self: &mut Asset_account, status: AccountStatus) {
    self.status = status
  }

  public fun get_table_id(): vector<u8> {
    table_id::encode(table_id::onchain_table_type(), TABLE_NAME)
  }

  public fun get_key_schemas(): vector<vector<u8>> {
    vector[b"address", b"address"]
  }

  public fun get_value_schemas(): vector<vector<u8>> {
    vector[b"u256", b"AccountStatus"]
  }

  public fun get_key_names(): vector<vector<u8>> {
    vector[b"asset_id", b"account"]
  }

  public fun get_value_names(): vector<vector<u8>> {
    vector[b"balance", b"status"]
  }

  public fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let dapp_key = dubhe_dapp_key::new();
    dapp_service::register_table(
            dapp_hub, 
            dapp_key,
            get_table_id(), 
            TABLE_NAME, 
            get_key_schemas(), 
            get_key_names(), 
            get_value_schemas(), 
            get_value_names(), 
            ctx
        );
  }

  public fun has(dapp_hub: &DappHub, asset_id: address, account: address): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    dapp_service::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub, asset_id: address, account: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    dapp_service::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_not_has(dapp_hub: &DappHub, asset_id: address, account: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    dapp_service::ensure_not_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun has_balance(dapp_hub: &DappHub, asset_id: address, account: address): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    dapp_service::has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun ensure_has_balance(dapp_hub: &DappHub, asset_id: address, account: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    dapp_service::ensure_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun ensure_not_has_balance(dapp_hub: &DappHub, asset_id: address, account: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    dapp_service::ensure_not_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun has_status(dapp_hub: &DappHub, asset_id: address, account: address): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    dapp_service::has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun ensure_has_status(dapp_hub: &DappHub, asset_id: address, account: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    dapp_service::ensure_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun ensure_not_has_status(dapp_hub: &DappHub, asset_id: address, account: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    dapp_service::ensure_not_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun delete(dapp_hub: &mut DappHub, asset_id: address, account: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    dapp_service::delete_record<DappKey>(dapp_hub, dubhe_dapp_key::new(), get_table_id(), key_tuple);
  }

  public fun get_balance(dapp_hub: &DappHub, asset_id: address, account: address): u256 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0);
    let mut bsc_type = sui::bcs::new(value);
    let balance = sui::bcs::peel_u256(&mut bsc_type);
    balance
  }

  public fun set_balance(dapp_hub: &mut DappHub, asset_id: address, account: address, balance: u256) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    let value = to_bytes(&balance);
    dapp_service::set_field(dapp_hub, dubhe_dapp_key::new(), get_table_id(), key_tuple, 0, value);
  }

  public fun get_status(dapp_hub: &DappHub, asset_id: address, account: address): AccountStatus {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1);
    let mut bsc_type = sui::bcs::new(value);
    let status = dubhe::dubhe_account_status::decode(&mut bsc_type);
    status
  }

  public fun set_status(dapp_hub: &mut DappHub, asset_id: address, account: address, status: AccountStatus) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    let value = dubhe::dubhe_account_status::encode(status);
    dapp_service::set_field(dapp_hub, dubhe_dapp_key::new(), get_table_id(), key_tuple, 1, value);
  }

  public fun get(dapp_hub: &DappHub, asset_id: address, account: address): (u256, AccountStatus) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    let mut bsc_type = sui::bcs::new(value_tuple);
    let balance = sui::bcs::peel_u256(&mut bsc_type);
    let status = dubhe::dubhe_account_status::decode(&mut bsc_type);
    (balance, status)
  }

  public fun set(dapp_hub: &mut DappHub, asset_id: address, account: address, balance: u256, status: AccountStatus) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    let value_tuple = encode(balance, status);
    dapp_service::set_record(dapp_hub, dubhe_dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun get_struct(dapp_hub: &DappHub, asset_id: address, account: address): Asset_account {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    decode(value_tuple)
  }

  public fun set_struct(dapp_hub: &mut DappHub, asset_id: address, account: address, asset_account: Asset_account) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&asset_id));
    key_tuple.push_back(to_bytes(&account));
    let value_tuple = encode_struct(asset_account);
    dapp_service::set_record(dapp_hub, dubhe_dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun encode(balance: u256, status: AccountStatus): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&balance));
    value_tuple.push_back(dubhe::dubhe_account_status::encode(status));
    value_tuple
  }

  public fun encode_struct(asset_account: Asset_account): vector<vector<u8>> {
    encode(asset_account.balance, asset_account.status)
  }

  public fun decode(data: vector<u8>): Asset_account {
    let mut bsc_type = sui::bcs::new(data);
    let balance = sui::bcs::peel_u256(&mut bsc_type);
    let status = dubhe::dubhe_account_status::decode(&mut bsc_type);
    Asset_account {
            balance,
            status,
        }
  }
}
