  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::component11 {

  use sui::bcs::{to_bytes};

  use dubhe::table_id;

  use dubhe::dapp_service::{Self, DappHub};

  use example::dapp_key;

  use example::dapp_key::DappKey;

  use example::direction;

  use example::direction::{Direction};

  const TABLE_NAME: vector<u8> = b"component11";

  public struct Component11 has copy, drop, store {
    value: u32,
    direction: Direction,
  }

  public fun new(value: u32, direction: Direction): Component11 {
    Component11 {
            value,
            direction,
        }
  }

  public fun value(self: &Component11): u32 {
    self.value
  }

  public fun direction(self: &Component11): Direction {
    self.direction
  }

  public fun update_value(self: &mut Component11, value: u32) {
    self.value = value
  }

  public fun update_direction(self: &mut Component11, direction: Direction) {
    self.direction = direction
  }

  public fun get_table_id(): vector<u8> {
    table_id::encode(table_id::onchain_table_type(), TABLE_NAME)
  }

  public fun get_key_schemas(): vector<vector<u8>> {
    vector[b"address"]
  }

  public fun get_value_schemas(): vector<vector<u8>> {
    vector[b"u32", b"Direction"]
  }

  public fun get_key_names(): vector<vector<u8>> {
    vector[b"player"]
  }

  public fun get_value_names(): vector<vector<u8>> {
    vector[b"value", b"direction"]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let dapp_key = dapp_key::new();
    dapp_service::register_table(
            dapp_hub, 
            dapp_key,
            get_table_id(), 
            TABLE_NAME, 
            get_key_schemas(), 
            get_key_names(), 
            get_value_schemas(), 
            get_value_names(), 
            ctx
        );
  }

  public fun has(dapp_hub: &DappHub, player: address): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    dapp_service::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub, player: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    dapp_service::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_not_has(dapp_hub: &DappHub, player: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    dapp_service::ensure_not_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun has_value(dapp_hub: &DappHub, player: address): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    dapp_service::has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun ensure_has_value(dapp_hub: &DappHub, player: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    dapp_service::ensure_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun ensure_not_has_value(dapp_hub: &DappHub, player: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    dapp_service::ensure_not_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun has_direction(dapp_hub: &DappHub, player: address): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    dapp_service::has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun ensure_has_direction(dapp_hub: &DappHub, player: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    dapp_service::ensure_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun ensure_not_has_direction(dapp_hub: &DappHub, player: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    dapp_service::ensure_not_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public(package) fun delete(dapp_hub: &mut DappHub, player: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    dapp_service::delete_record<DappKey>(dapp_hub, dapp_key::new(), get_table_id(), key_tuple);
  }

  public fun get_value(dapp_hub: &DappHub, player: address): u32 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0);
    let mut bsc_type = sui::bcs::new(value);
    let value = sui::bcs::peel_u32(&mut bsc_type);
    value
  }

  public(package) fun set_value(dapp_hub: &mut DappHub, player: address, value: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    let value = to_bytes(&value);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 0, value);
  }

  public fun get_direction(dapp_hub: &DappHub, player: address): Direction {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1);
    let mut bsc_type = sui::bcs::new(value);
    let direction = example::direction::decode(&mut bsc_type);
    direction
  }

  public(package) fun set_direction(dapp_hub: &mut DappHub, player: address, direction: Direction) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    let value = example::direction::encode(direction);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 1, value);
  }

  public fun get(dapp_hub: &DappHub, player: address): (u32, Direction) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    let mut bsc_type = sui::bcs::new(value_tuple);
    let value = sui::bcs::peel_u32(&mut bsc_type);
    let direction = example::direction::decode(&mut bsc_type);
    (value, direction)
  }

  public(package) fun set(dapp_hub: &mut DappHub, player: address, value: u32, direction: Direction) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    let value_tuple = encode(value, direction);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun get_struct(dapp_hub: &DappHub, player: address): Component11 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    decode(value_tuple)
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, player: address, component11: Component11) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    let value_tuple = encode_struct(component11);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun encode(value: u32, direction: Direction): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&value));
    value_tuple.push_back(example::direction::encode(direction));
    value_tuple
  }

  public fun encode_struct(component11: Component11): vector<vector<u8>> {
    encode(component11.value, component11.direction)
  }

  public fun decode(data: vector<u8>): Component11 {
    let mut bsc_type = sui::bcs::new(data);
    let value = sui::bcs::peel_u32(&mut bsc_type);
    let direction = example::direction::decode(&mut bsc_type);
    Component11 {
            value,
            direction,
        }
  }
}
