  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module test_project::test_project_errors {

  #[error]

  const ASSET_NOT_FOUND: vector<u8> = b"Asset not found";

  public fun asset_not_found_error(condition: bool) {
    assert!(condition, ASSET_NOT_FOUND)
  }

  #[error]

  const ASSET_ALREADY_FROZEN: vector<u8> = b"Asset already frozen";

  public fun asset_already_frozen_error(condition: bool) {
    assert!(condition, ASSET_ALREADY_FROZEN)
  }
}
