  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::deploy_hook {

  use dubhe::dapp_service::DappHub;
  use example::resource0;

  public(package) fun run(_dapp_hub: &mut DappHub, _ctx: &mut TxContext) {
    resource0::set(_dapp_hub, 0);
  }
}
