FROM node:22-bookworm-slim

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH

ARG NUMERON_REPO_URL=https://github.com/0xobelisk/numeron-channel-mvp.git
ARG NUMERON_REPO_REF=main
ARG NEXT_PUBLIC_PRIVATE_KEY
ARG NEXT_PUBLIC_CHANNEL_URL
ARG NEXT_PUBLIC_CHANNEL_FEED_UI=true
ARG NEXT_PUBLIC_CHANNEL_VERBOSE_LOGS=true
ARG NEXT_PUBLIC_REMOTE_INTENT_MOVE_DURATION_MS=56
ARG NEXT_PUBLIC_FORCE_CHANNEL_SUBMIT=true
ARG NEXT_PUBLIC_CHANNEL_REGISTER_SENDER=
ARG NEXT_PUBLIC_FAST_MOVE_DURATION_MS=48

ENV NEXT_PUBLIC_PRIVATE_KEY=$NEXT_PUBLIC_PRIVATE_KEY
ENV NEXT_PUBLIC_CHANNEL_URL=$NEXT_PUBLIC_CHANNEL_URL
ENV NEXT_PUBLIC_CHANNEL_FEED_UI=$NEXT_PUBLIC_CHANNEL_FEED_UI
ENV NEXT_PUBLIC_CHANNEL_VERBOSE_LOGS=$NEXT_PUBLIC_CHANNEL_VERBOSE_LOGS
ENV NEXT_PUBLIC_REMOTE_INTENT_MOVE_DURATION_MS=$NEXT_PUBLIC_REMOTE_INTENT_MOVE_DURATION_MS
ENV NEXT_PUBLIC_FORCE_CHANNEL_SUBMIT=$NEXT_PUBLIC_FORCE_CHANNEL_SUBMIT
ENV NEXT_PUBLIC_CHANNEL_REGISTER_SENDER=$NEXT_PUBLIC_CHANNEL_REGISTER_SENDER
ENV NEXT_PUBLIC_FAST_MOVE_DURATION_MS=$NEXT_PUBLIC_FAST_MOVE_DURATION_MS

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
  && rm -rf /var/lib/apt/lists/* \
  && corepack enable

WORKDIR /app

COPY packages/sui-client ./packages/sui-client

RUN git clone --depth 1 --branch "$NUMERON_REPO_REF" "$NUMERON_REPO_URL" /app/numeron-channel-mvp

WORKDIR /app/numeron-channel-mvp

RUN pnpm install --frozen-lockfile
RUN pnpm --filter web build

WORKDIR /app/numeron-channel-mvp/apps/web

EXPOSE 3000

CMD ["sh", "-lc", "PORT=${PORT:-3000} pnpm start"]
