// @generated by protobuf-ts 2.11.1 with parameter force_server_none,optimize_code_size,ts_nocheck
// @generated from protobuf file "dubhe_grpc.proto" (package "dubhe_grpc", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from '@protobuf-ts/runtime-rpc';
import { MessageType } from '@protobuf-ts/runtime';
import { Struct } from './google/protobuf/struct';
/**
 * Universal query request with comprehensive options
 *
 * @generated from protobuf message dubhe_grpc.QueryRequest
 */
export interface QueryRequest {
  /**
   * Required: table name to query
   *
   * @generated from protobuf field: string table_name = 1
   */
  tableName: string;
  /**
   * Optional: specific fields to select (empty means SELECT *)
   *
   * @generated from protobuf field: repeated string select_fields = 2
   */
  selectFields: string[];
  /**
   * Optional: filter conditions
   *
   * @generated from protobuf field: repeated dubhe_grpc.FilterCondition filters = 3
   */
  filters: FilterCondition[];
  /**
   * Optional: sorting specifications
   *
   * @generated from protobuf field: repeated dubhe_grpc.SortSpecification sorts = 4
   */
  sorts: SortSpecification[];
  /**
   * Optional: pagination parameters
   *
   * @generated from protobuf field: optional dubhe_grpc.PaginationRequest pagination = 5
   */
  pagination?: PaginationRequest;
  /**
   * Optional: whether to include total count for pagination
   *
   * @generated from protobuf field: bool include_total_count = 6
   */
  includeTotalCount: boolean;
}
/**
 * Filter condition for WHERE clauses
 *
 * @generated from protobuf message dubhe_grpc.FilterCondition
 */
export interface FilterCondition {
  /**
   * Field name to filter on
   *
   * @generated from protobuf field: string field_name = 1
   */
  fieldName: string;
  /**
   * Filter operator
   *
   * @generated from protobuf field: dubhe_grpc.FilterOperator operator = 2
   */
  operator: FilterOperator;
  /**
   * Filter value(s)
   *
   * @generated from protobuf field: dubhe_grpc.FilterValue value = 3
   */
  value?: FilterValue;
}
/**
 * Filter value that can be various types
 *
 * @generated from protobuf message dubhe_grpc.FilterValue
 */
export interface FilterValue {
  /**
   * @generated from protobuf oneof: value
   */
  value:
    | {
        oneofKind: 'stringValue';
        /**
         * @generated from protobuf field: string string_value = 1
         */
        stringValue: string;
      }
    | {
        oneofKind: 'intValue';
        /**
         * @generated from protobuf field: int64 int_value = 2
         */
        intValue: bigint;
      }
    | {
        oneofKind: 'floatValue';
        /**
         * @generated from protobuf field: double float_value = 3
         */
        floatValue: number;
      }
    | {
        oneofKind: 'boolValue';
        /**
         * @generated from protobuf field: bool bool_value = 4
         */
        boolValue: boolean;
      }
    | {
        oneofKind: 'stringList';
        /**
         * @generated from protobuf field: dubhe_grpc.StringList string_list = 5
         */
        stringList: StringList; // For IN/NOT_IN operations
      }
    | {
        oneofKind: 'intList';
        /**
         * @generated from protobuf field: dubhe_grpc.IntList int_list = 6
         */
        intList: IntList; // For IN/NOT_IN operations
      }
    | {
        oneofKind: 'range';
        /**
         * @generated from protobuf field: dubhe_grpc.ValueRange range = 7
         */
        range: ValueRange; // For BETWEEN operations
      }
    | {
        oneofKind: 'nullValue';
        /**
         * @generated from protobuf field: bool null_value = 8
         */
        nullValue: boolean; // For NULL checks
      }
    | {
        oneofKind: undefined;
      };
}
/**
 * List of string values
 *
 * @generated from protobuf message dubhe_grpc.StringList
 */
export interface StringList {
  /**
   * @generated from protobuf field: repeated string values = 1
   */
  values: string[];
}
/**
 * List of integer values
 *
 * @generated from protobuf message dubhe_grpc.IntList
 */
export interface IntList {
  /**
   * @generated from protobuf field: repeated int64 values = 1
   */
  values: bigint[];
}
/**
 * Value range for BETWEEN operations
 *
 * @generated from protobuf message dubhe_grpc.ValueRange
 */
export interface ValueRange {
  /**
   * @generated from protobuf oneof: start
   */
  start:
    | {
        oneofKind: 'stringStart';
        /**
         * @generated from protobuf field: string string_start = 1
         */
        stringStart: string;
      }
    | {
        oneofKind: 'intStart';
        /**
         * @generated from protobuf field: int64 int_start = 2
         */
        intStart: bigint;
      }
    | {
        oneofKind: 'floatStart';
        /**
         * @generated from protobuf field: double float_start = 3
         */
        floatStart: number;
      }
    | {
        oneofKind: undefined;
      };
  /**
   * @generated from protobuf oneof: end
   */
  end:
    | {
        oneofKind: 'stringEnd';
        /**
         * @generated from protobuf field: string string_end = 4
         */
        stringEnd: string;
      }
    | {
        oneofKind: 'intEnd';
        /**
         * @generated from protobuf field: int64 int_end = 5
         */
        intEnd: bigint;
      }
    | {
        oneofKind: 'floatEnd';
        /**
         * @generated from protobuf field: double float_end = 6
         */
        floatEnd: number;
      }
    | {
        oneofKind: undefined;
      };
}
/**
 * Sort specification
 *
 * @generated from protobuf message dubhe_grpc.SortSpecification
 */
export interface SortSpecification {
  /**
   * Field name to sort by
   *
   * @generated from protobuf field: string field_name = 1
   */
  fieldName: string;
  /**
   * Sort direction
   *
   * @generated from protobuf field: dubhe_grpc.SortDirection direction = 2
   */
  direction: SortDirection;
  /**
   * Optional: sort priority (lower number = higher priority)
   *
   * @generated from protobuf field: optional int32 priority = 3
   */
  priority?: number;
}
/**
 * Pagination request
 *
 * @generated from protobuf message dubhe_grpc.PaginationRequest
 */
export interface PaginationRequest {
  /**
   * Page number (1-based)
   *
   * @generated from protobuf field: int32 page = 1
   */
  page: number;
  /**
   * Number of items per page
   *
   * @generated from protobuf field: int32 page_size = 2
   */
  pageSize: number;
  /**
   * Optional: offset-based pagination (alternative to page-based)
   *
   * @generated from protobuf field: optional int32 offset = 3
   */
  offset?: number;
}
/**
 * Query response
 *
 * @generated from protobuf message dubhe_grpc.QueryResponse
 */
export interface QueryResponse {
  /**
   * Query results
   *
   * @generated from protobuf field: repeated google.protobuf.Struct rows = 1
   */
  rows: Struct[];
  /**
   * Pagination info
   *
   * @generated from protobuf field: optional dubhe_grpc.PaginationResponse pagination = 2
   */
  pagination?: PaginationResponse;
}
/**
 * Pagination response
 *
 * @generated from protobuf message dubhe_grpc.PaginationResponse
 */
export interface PaginationResponse {
  /**
   * @generated from protobuf field: int32 current_page = 1
   */
  currentPage: number; // Current page number
  /**
   * @generated from protobuf field: int32 page_size = 2
   */
  pageSize: number; // Items per page
  /**
   * @generated from protobuf field: int64 total_items = 3
   */
  totalItems: bigint; // Total number of items
  /**
   * @generated from protobuf field: int32 total_pages = 4
   */
  totalPages: number; // Total number of pages
  /**
   * @generated from protobuf field: bool has_next_page = 5
   */
  hasNextPage: boolean; // Whether there's a next page
  /**
   * @generated from protobuf field: bool has_previous_page = 6
   */
  hasPreviousPage: boolean; // Whether there's a previous page
}
/**
 * Subscribe request
 *
 * @generated from protobuf message dubhe_grpc.SubscribeRequest
 */
export interface SubscribeRequest {
  /**
   * @generated from protobuf field: repeated string table_ids = 1
   */
  tableIds: string[]; // Multiple table IDs to subscribe to. Empty array means subscribe to all tables.
}
/**
 * Table update stream
 *
 * @generated from protobuf message dubhe_grpc.TableChange
 */
export interface TableChange {
  /**
   * @generated from protobuf field: string table_id = 1
   */
  tableId: string;
  /**
   * @generated from protobuf field: google.protobuf.Struct data = 2
   */
  data?: Struct;
}
/**
 * Filter operators
 *
 * @generated from protobuf enum dubhe_grpc.FilterOperator
 */
export enum FilterOperator {
  /**
   * =
   *
   * @generated from protobuf enum value: EQUALS = 0;
   */
  EQUALS = 0,
  /**
   * !=
   *
   * @generated from protobuf enum value: NOT_EQUALS = 1;
   */
  NOT_EQUALS = 1,
  /**
   * >
   *
   * @generated from protobuf enum value: GREATER_THAN = 2;
   */
  GREATER_THAN = 2,
  /**
   * >=
   *
   * @generated from protobuf enum value: GREATER_THAN_EQUAL = 3;
   */
  GREATER_THAN_EQUAL = 3,
  /**
   * <
   *
   * @generated from protobuf enum value: LESS_THAN = 4;
   */
  LESS_THAN = 4,
  /**
   * <=
   *
   * @generated from protobuf enum value: LESS_THAN_EQUAL = 5;
   */
  LESS_THAN_EQUAL = 5,
  /**
   * LIKE (pattern matching)
   *
   * @generated from protobuf enum value: LIKE = 6;
   */
  LIKE = 6,
  /**
   * NOT LIKE
   *
   * @generated from protobuf enum value: NOT_LIKE = 7;
   */
  NOT_LIKE = 7,
  /**
   * IN (value1, value2, ...)
   *
   * @generated from protobuf enum value: IN = 8;
   */
  IN = 8,
  /**
   * NOT IN (value1, value2, ...)
   *
   * @generated from protobuf enum value: NOT_IN = 9;
   */
  NOT_IN = 9,
  /**
   * IS NULL
   *
   * @generated from protobuf enum value: IS_NULL = 10;
   */
  IS_NULL = 10,
  /**
   * IS NOT NULL
   *
   * @generated from protobuf enum value: IS_NOT_NULL = 11;
   */
  IS_NOT_NULL = 11,
  /**
   * BETWEEN value1 AND value2
   *
   * @generated from protobuf enum value: BETWEEN = 12;
   */
  BETWEEN = 12,
  /**
   * NOT BETWEEN value1 AND value2
   *
   * @generated from protobuf enum value: NOT_BETWEEN = 13;
   */
  NOT_BETWEEN = 13
}
/**
 * Sort direction
 *
 * @generated from protobuf enum dubhe_grpc.SortDirection
 */
export enum SortDirection {
  /**
   * ASC
   *
   * @generated from protobuf enum value: ASCENDING = 0;
   */
  ASCENDING = 0,
  /**
   * DESC
   *
   * @generated from protobuf enum value: DESCENDING = 1;
   */
  DESCENDING = 1
}
// @generated message type with reflection information, may provide speed optimized methods
class QueryRequest$Type extends MessageType<QueryRequest> {
  constructor() {
    super('dubhe_grpc.QueryRequest', [
      { no: 1, name: 'table_name', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
      {
        no: 2,
        name: 'select_fields',
        kind: 'scalar',
        repeat: 2 /*RepeatType.UNPACKED*/,
        T: 9 /*ScalarType.STRING*/
      },
      {
        no: 3,
        name: 'filters',
        kind: 'message',
        repeat: 2 /*RepeatType.UNPACKED*/,
        T: () => FilterCondition
      },
      {
        no: 4,
        name: 'sorts',
        kind: 'message',
        repeat: 2 /*RepeatType.UNPACKED*/,
        T: () => SortSpecification
      },
      { no: 5, name: 'pagination', kind: 'message', T: () => PaginationRequest },
      { no: 6, name: 'include_total_count', kind: 'scalar', T: 8 /*ScalarType.BOOL*/ }
    ]);
  }
}
/**
 * @generated MessageType for protobuf message dubhe_grpc.QueryRequest
 */
export const QueryRequest = new QueryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FilterCondition$Type extends MessageType<FilterCondition> {
  constructor() {
    super('dubhe_grpc.FilterCondition', [
      { no: 1, name: 'field_name', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
      {
        no: 2,
        name: 'operator',
        kind: 'enum',
        T: () => ['dubhe_grpc.FilterOperator', FilterOperator]
      },
      { no: 3, name: 'value', kind: 'message', T: () => FilterValue }
    ]);
  }
}
/**
 * @generated MessageType for protobuf message dubhe_grpc.FilterCondition
 */
export const FilterCondition = new FilterCondition$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FilterValue$Type extends MessageType<FilterValue> {
  constructor() {
    super('dubhe_grpc.FilterValue', [
      { no: 1, name: 'string_value', kind: 'scalar', oneof: 'value', T: 9 /*ScalarType.STRING*/ },
      {
        no: 2,
        name: 'int_value',
        kind: 'scalar',
        oneof: 'value',
        T: 3 /*ScalarType.INT64*/,
        L: 0 /*LongType.BIGINT*/
      },
      { no: 3, name: 'float_value', kind: 'scalar', oneof: 'value', T: 1 /*ScalarType.DOUBLE*/ },
      { no: 4, name: 'bool_value', kind: 'scalar', oneof: 'value', T: 8 /*ScalarType.BOOL*/ },
      { no: 5, name: 'string_list', kind: 'message', oneof: 'value', T: () => StringList },
      { no: 6, name: 'int_list', kind: 'message', oneof: 'value', T: () => IntList },
      { no: 7, name: 'range', kind: 'message', oneof: 'value', T: () => ValueRange },
      { no: 8, name: 'null_value', kind: 'scalar', oneof: 'value', T: 8 /*ScalarType.BOOL*/ }
    ]);
  }
}
/**
 * @generated MessageType for protobuf message dubhe_grpc.FilterValue
 */
export const FilterValue = new FilterValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StringList$Type extends MessageType<StringList> {
  constructor() {
    super('dubhe_grpc.StringList', [
      {
        no: 1,
        name: 'values',
        kind: 'scalar',
        repeat: 2 /*RepeatType.UNPACKED*/,
        T: 9 /*ScalarType.STRING*/
      }
    ]);
  }
}
/**
 * @generated MessageType for protobuf message dubhe_grpc.StringList
 */
export const StringList = new StringList$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IntList$Type extends MessageType<IntList> {
  constructor() {
    super('dubhe_grpc.IntList', [
      {
        no: 1,
        name: 'values',
        kind: 'scalar',
        repeat: 1 /*RepeatType.PACKED*/,
        T: 3 /*ScalarType.INT64*/,
        L: 0 /*LongType.BIGINT*/
      }
    ]);
  }
}
/**
 * @generated MessageType for protobuf message dubhe_grpc.IntList
 */
export const IntList = new IntList$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ValueRange$Type extends MessageType<ValueRange> {
  constructor() {
    super('dubhe_grpc.ValueRange', [
      { no: 1, name: 'string_start', kind: 'scalar', oneof: 'start', T: 9 /*ScalarType.STRING*/ },
      {
        no: 2,
        name: 'int_start',
        kind: 'scalar',
        oneof: 'start',
        T: 3 /*ScalarType.INT64*/,
        L: 0 /*LongType.BIGINT*/
      },
      { no: 3, name: 'float_start', kind: 'scalar', oneof: 'start', T: 1 /*ScalarType.DOUBLE*/ },
      { no: 4, name: 'string_end', kind: 'scalar', oneof: 'end', T: 9 /*ScalarType.STRING*/ },
      {
        no: 5,
        name: 'int_end',
        kind: 'scalar',
        oneof: 'end',
        T: 3 /*ScalarType.INT64*/,
        L: 0 /*LongType.BIGINT*/
      },
      { no: 6, name: 'float_end', kind: 'scalar', oneof: 'end', T: 1 /*ScalarType.DOUBLE*/ }
    ]);
  }
}
/**
 * @generated MessageType for protobuf message dubhe_grpc.ValueRange
 */
export const ValueRange = new ValueRange$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SortSpecification$Type extends MessageType<SortSpecification> {
  constructor() {
    super('dubhe_grpc.SortSpecification', [
      { no: 1, name: 'field_name', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
      {
        no: 2,
        name: 'direction',
        kind: 'enum',
        T: () => ['dubhe_grpc.SortDirection', SortDirection]
      },
      { no: 3, name: 'priority', kind: 'scalar', opt: true, T: 5 /*ScalarType.INT32*/ }
    ]);
  }
}
/**
 * @generated MessageType for protobuf message dubhe_grpc.SortSpecification
 */
export const SortSpecification = new SortSpecification$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PaginationRequest$Type extends MessageType<PaginationRequest> {
  constructor() {
    super('dubhe_grpc.PaginationRequest', [
      { no: 1, name: 'page', kind: 'scalar', T: 5 /*ScalarType.INT32*/ },
      { no: 2, name: 'page_size', kind: 'scalar', T: 5 /*ScalarType.INT32*/ },
      { no: 3, name: 'offset', kind: 'scalar', opt: true, T: 5 /*ScalarType.INT32*/ }
    ]);
  }
}
/**
 * @generated MessageType for protobuf message dubhe_grpc.PaginationRequest
 */
export const PaginationRequest = new PaginationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QueryResponse$Type extends MessageType<QueryResponse> {
  constructor() {
    super('dubhe_grpc.QueryResponse', [
      { no: 1, name: 'rows', kind: 'message', repeat: 2 /*RepeatType.UNPACKED*/, T: () => Struct },
      { no: 2, name: 'pagination', kind: 'message', T: () => PaginationResponse }
    ]);
  }
}
/**
 * @generated MessageType for protobuf message dubhe_grpc.QueryResponse
 */
export const QueryResponse = new QueryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PaginationResponse$Type extends MessageType<PaginationResponse> {
  constructor() {
    super('dubhe_grpc.PaginationResponse', [
      { no: 1, name: 'current_page', kind: 'scalar', T: 5 /*ScalarType.INT32*/ },
      { no: 2, name: 'page_size', kind: 'scalar', T: 5 /*ScalarType.INT32*/ },
      {
        no: 3,
        name: 'total_items',
        kind: 'scalar',
        T: 3 /*ScalarType.INT64*/,
        L: 0 /*LongType.BIGINT*/
      },
      { no: 4, name: 'total_pages', kind: 'scalar', T: 5 /*ScalarType.INT32*/ },
      { no: 5, name: 'has_next_page', kind: 'scalar', T: 8 /*ScalarType.BOOL*/ },
      { no: 6, name: 'has_previous_page', kind: 'scalar', T: 8 /*ScalarType.BOOL*/ }
    ]);
  }
}
/**
 * @generated MessageType for protobuf message dubhe_grpc.PaginationResponse
 */
export const PaginationResponse = new PaginationResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubscribeRequest$Type extends MessageType<SubscribeRequest> {
  constructor() {
    super('dubhe_grpc.SubscribeRequest', [
      {
        no: 1,
        name: 'table_ids',
        kind: 'scalar',
        repeat: 2 /*RepeatType.UNPACKED*/,
        T: 9 /*ScalarType.STRING*/
      }
    ]);
  }
}
/**
 * @generated MessageType for protobuf message dubhe_grpc.SubscribeRequest
 */
export const SubscribeRequest = new SubscribeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TableChange$Type extends MessageType<TableChange> {
  constructor() {
    super('dubhe_grpc.TableChange', [
      { no: 1, name: 'table_id', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
      { no: 2, name: 'data', kind: 'message', T: () => Struct }
    ]);
  }
}
/**
 * @generated MessageType for protobuf message dubhe_grpc.TableChange
 */
export const TableChange = new TableChange$Type();
/**
 * @generated ServiceType for protobuf service dubhe_grpc.DubheGrpc
 */
export const DubheGrpc = new ServiceType('dubhe_grpc.DubheGrpc', [
  { name: 'QueryTable', options: {}, I: QueryRequest, O: QueryResponse },
  {
    name: 'SubscribeTable',
    serverStreaming: true,
    options: {},
    I: SubscribeRequest,
    O: TableChange
  }
]);
