  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::deploy_hook {

  use dubhe::dapp_service::DappHub;
  use dubhe::dubhe_config;
  use dubhe::bridge_config;
  use dubhe::dubhe_asset_id;
  use dubhe::wrapper_system;
  use sui::sui::SUI;
  use dubhe::dubhe::DUBHE;
  use dubhe::dapp_fee_config;
  use std::ascii::{string, String};

  public(package) fun run(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let next_asset_id = 0;
      // 0.3% swap fee
    let swap_fee = 30;
    let fee_to = ctx.sender();
    let max_swap_path_len = 6;
    dubhe_config::set(
      dapp_hub, 
      next_asset_id, 
      swap_fee, 
      fee_to, 
      max_swap_path_len,
      ctx.sender()
    );

    // set bridge config
    bridge_config::set(dapp_hub, string(b"Dubhe OS"), 10 * 10000000, 2 * 10000000, true);
    bridge_config::set(dapp_hub, string(b"Aptos"), 10 * 10000000, 2 * 10000000, true);

    // set free credit
    let free_credit = 1000 * 10000000;
    let base_fee = 80000;
    let byte_fee = 500;
    dapp_fee_config::set(dapp_hub, free_credit, base_fee, byte_fee);

    let sui_asset_id = wrapper_system::do_register<SUI>(
      dapp_hub,
      string(b"Wrapped SUI"),
      string(b"wSUI"),
      string(b"Wrapped SUI"),
    9,
    string(b"https://cryptologos.cc/logos/sui-sui-logo.png?v=040"),
    );
    let dubhe_asset_id = wrapper_system::do_register<DUBHE>(
      dapp_hub,
      string(b"Wrapped DUBHE"),
      string(b"wDUBHE"),
      string(b"Wrapped DUBHE"),
      7,
      string(b"https://raw.githubusercontent.com/0xobelisk/dubhe/refs/heads/main/assets/logo.jpg"),
    );
    dubhe_asset_id::set(dapp_hub, dubhe_asset_id);

    std::debug::print(&sui_asset_id);
    std::debug::print(&dubhe_asset_id);
    
  }
}
