  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module test_project::test_project_deploy_hook {

  use dubhe::dapp_hub::DappHub;

  use test_project::test_project_dapp_key;
  use test_project::test_project_map_config;
  use test_project::test_project_encounter;

  public(package) fun run(dapp_hub: &mut DappHub, _ctx: &mut TxContext) {
    test_project_map_config::set(dapp_hub, 100, 100);
    

  }
}
