  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dms::message_too_long_error {

  #[error]

  const MessageTooLong: vector<u8> = b"Message is too long";

  /// Get the error message.

  public fun message(): vector<u8> {
    MessageTooLong
  }

  /// Abort execution with the given error code.

  public fun emit() {
    abort MessageTooLong
  }

  /// Require that the given condition is true, otherwise abort with the given error code.

  public fun require(condition: bool) {
    if (!condition) { emit() }
  }
}
