  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::direction {

  use sui::bcs::{BCS, to_bytes, peel_enum_tag};

  public enum Direction has copy, drop, store {
        East,North,South,West
    }

  public fun new_east(): Direction {
    Direction::East
  }

  public fun new_north(): Direction {
    Direction::North
  }

  public fun new_south(): Direction {
    Direction::South
  }

  public fun new_west(): Direction {
    Direction::West
  }

  public fun encode(self: Direction): vector<u8> {
    to_bytes(&self)
  }

  public fun decode(bytes: &mut BCS): Direction {
    match(peel_enum_tag(bytes)) {
            0 => Direction::East,
            1 => Direction::North,
            2 => Direction::South,
            3 => Direction::West,
            _ => abort,
        }
  }
}
