  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::status {

  use sui::bcs::{BCS, to_bytes, peel_enum_tag};

  public enum Status has copy, drop, store {
        Caught,Fled,Missed
    }

  public fun new_caught(): Status {
    Status::Caught
  }

  public fun new_fled(): Status {
    Status::Fled
  }

  public fun new_missed(): Status {
    Status::Missed
  }

  public fun encode(self: Status): vector<u8> {
    to_bytes(&self)
  }

  public fun decode(bytes: &mut BCS): Status {
    match(peel_enum_tag(bytes)) {
            0 => Status::Caught,
            1 => Status::Fled,
            2 => Status::Missed,
            _ => abort,
        }
  }
}
