  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dms::message_set_event {

  use sui::event;

  use std::ascii::String;

  public struct MessageSetEvent has copy, drop {
    sender: address,
    message: String,
  }

  public fun new(sender: address, message: String): MessageSetEvent {
    MessageSetEvent {
                                   sender,message
                               }
  }

  public fun emit(sender: address, message: String) {
    event::emit(MessageSetEvent {
                                   sender,message
                               });
  }
}
