  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::resource6 {

  use sui::bcs::{to_bytes};

  use dubhe::table_id;

  use dubhe::dapp_service::{Self, DappHub};

  use example::dapp_key;

  use example::dapp_key::DappKey;

  const TABLE_NAME: vector<u8> = b"resource6";

  public struct Resource6 has copy, drop, store {
    value1: u32,
    value2: u32,
  }

  public fun new(value1: u32, value2: u32): Resource6 {
    Resource6 {
            value1,
            value2,
        }
  }

  public fun value1(self: &Resource6): u32 {
    self.value1
  }

  public fun value2(self: &Resource6): u32 {
    self.value2
  }

  public fun update_value1(self: &mut Resource6, value1: u32) {
    self.value1 = value1
  }

  public fun update_value2(self: &mut Resource6, value2: u32) {
    self.value2 = value2
  }

  public fun get_table_id(): vector<u8> {
    table_id::encode(table_id::onchain_table_type(), TABLE_NAME)
  }

  public fun get_key_schemas(): vector<vector<u8>> {
    vector[b"address", b"u32", b"u32"]
  }

  public fun get_value_schemas(): vector<vector<u8>> {
    vector[b"u32", b"u32"]
  }

  public fun get_key_names(): vector<vector<u8>> {
    vector[b"player", b"id1", b"id2"]
  }

  public fun get_value_names(): vector<vector<u8>> {
    vector[b"value1", b"value2"]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let dapp_key = dapp_key::new();
    dapp_service::register_table(
            dapp_hub, 
            dapp_key,
            get_table_id(), 
            TABLE_NAME, 
            get_key_schemas(), 
            get_key_names(), 
            get_value_schemas(), 
            get_value_names(), 
            ctx
        );
  }

  public fun has(dapp_hub: &DappHub, player: address, id1: u32, id2: u32): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    dapp_service::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub, player: address, id1: u32, id2: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    dapp_service::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_not_has(dapp_hub: &DappHub, player: address, id1: u32, id2: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    dapp_service::ensure_not_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun has_value1(dapp_hub: &DappHub, player: address, id1: u32, id2: u32): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    dapp_service::has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun ensure_has_value1(dapp_hub: &DappHub, player: address, id1: u32, id2: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    dapp_service::ensure_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun ensure_not_has_value1(dapp_hub: &DappHub, player: address, id1: u32, id2: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    dapp_service::ensure_not_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun has_value2(dapp_hub: &DappHub, player: address, id1: u32, id2: u32): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    dapp_service::has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun ensure_has_value2(dapp_hub: &DappHub, player: address, id1: u32, id2: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    dapp_service::ensure_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun ensure_not_has_value2(dapp_hub: &DappHub, player: address, id1: u32, id2: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    dapp_service::ensure_not_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public(package) fun delete(dapp_hub: &mut DappHub, player: address, id1: u32, id2: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    dapp_service::delete_record<DappKey>(dapp_hub, dapp_key::new(), get_table_id(), key_tuple);
  }

  public fun get_value1(dapp_hub: &DappHub, player: address, id1: u32, id2: u32): u32 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0);
    let mut bsc_type = sui::bcs::new(value);
    let value1 = sui::bcs::peel_u32(&mut bsc_type);
    value1
  }

  public(package) fun set_value1(dapp_hub: &mut DappHub, player: address, id1: u32, id2: u32, value1: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    let value = to_bytes(&value1);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 0, value);
  }

  public fun get_value2(dapp_hub: &DappHub, player: address, id1: u32, id2: u32): u32 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1);
    let mut bsc_type = sui::bcs::new(value);
    let value2 = sui::bcs::peel_u32(&mut bsc_type);
    value2
  }

  public(package) fun set_value2(dapp_hub: &mut DappHub, player: address, id1: u32, id2: u32, value2: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    let value = to_bytes(&value2);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 1, value);
  }

  public fun get(dapp_hub: &DappHub, player: address, id1: u32, id2: u32): (u32, u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    let mut bsc_type = sui::bcs::new(value_tuple);
    let value1 = sui::bcs::peel_u32(&mut bsc_type);
    let value2 = sui::bcs::peel_u32(&mut bsc_type);
    (value1, value2)
  }

  public(package) fun set(dapp_hub: &mut DappHub, player: address, id1: u32, id2: u32, value1: u32, value2: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    let value_tuple = encode(value1, value2);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun get_struct(dapp_hub: &DappHub, player: address, id1: u32, id2: u32): Resource6 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    decode(value_tuple)
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, player: address, id1: u32, id2: u32, resource6: Resource6) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id1));
    key_tuple.push_back(to_bytes(&id2));
    let value_tuple = encode_struct(resource6);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun encode(value1: u32, value2: u32): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&value1));
    value_tuple.push_back(to_bytes(&value2));
    value_tuple
  }

  public fun encode_struct(resource6: Resource6): vector<vector<u8>> {
    encode(resource6.value1, resource6.value2)
  }

  public fun decode(data: vector<u8>): Resource6 {
    let mut bsc_type = sui::bcs::new(data);
    let value1 = sui::bcs::peel_u32(&mut bsc_type);
    let value2 = sui::bcs::peel_u32(&mut bsc_type);
    Resource6 {
            value1,
            value2,
        }
  }
}
