  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::resource5 {

  use sui::bcs::{to_bytes};

  use dubhe::table_id;

  use dubhe::dapp_service::{Self, DappHub};

  use example::dapp_key;

  use example::dapp_key::DappKey;

  const TABLE_NAME: vector<u8> = b"resource5";

  public fun get_table_id(): vector<u8> {
    table_id::encode(table_id::onchain_table_type(), TABLE_NAME)
  }

  public fun get_key_schemas(): vector<vector<u8>> {
    vector[b"address", b"u32"]
  }

  public fun get_value_schemas(): vector<vector<u8>> {
    vector[b"u32"]
  }

  public fun get_key_names(): vector<vector<u8>> {
    vector[b"player", b"id"]
  }

  public fun get_value_names(): vector<vector<u8>> {
    vector[b"value"]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let dapp_key = dapp_key::new();
    dapp_service::register_table(
            dapp_hub, 
            dapp_key,
            get_table_id(), 
            TABLE_NAME, 
            get_key_schemas(), 
            get_key_names(), 
            get_value_schemas(), 
            get_value_names(), 
            ctx
        );
  }

  public fun has(dapp_hub: &DappHub, player: address, id: u32): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id));
    dapp_service::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub, player: address, id: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id));
    dapp_service::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_not_has(dapp_hub: &DappHub, player: address, id: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id));
    dapp_service::ensure_not_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public(package) fun delete(dapp_hub: &mut DappHub, player: address, id: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id));
    dapp_service::delete_record<DappKey>(dapp_hub, dapp_key::new(), get_table_id(), key_tuple);
  }

  public fun get(dapp_hub: &DappHub, player: address, id: u32): u32 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0);
    let mut bsc_type = sui::bcs::new(value);
    let value = sui::bcs::peel_u32(&mut bsc_type);
    value
  }

  public(package) fun set(dapp_hub: &mut DappHub, player: address, id: u32, value: u32) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&player));
    key_tuple.push_back(to_bytes(&id));
    let value_tuple = encode(value);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun encode(value: u32): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&value));
    value_tuple
  }
}
