  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::resource2 {

  use sui::bcs::{to_bytes};

  use dubhe::table_id;

  use dubhe::dapp_service::{Self, DappHub};

  use example::dapp_key;

  use example::dapp_key::DappKey;

  use example::direction;

  use example::direction::{Direction};

  const TABLE_NAME: vector<u8> = b"resource2";

  public struct Resource2 has copy, drop, store {
    player: address,
    value: u32,
    direction: Direction,
  }

  public fun new(player: address, value: u32, direction: Direction): Resource2 {
    Resource2 {
            player,
            value,
            direction,
        }
  }

  public fun player(self: &Resource2): address {
    self.player
  }

  public fun value(self: &Resource2): u32 {
    self.value
  }

  public fun direction(self: &Resource2): Direction {
    self.direction
  }

  public fun update_player(self: &mut Resource2, player: address) {
    self.player = player
  }

  public fun update_value(self: &mut Resource2, value: u32) {
    self.value = value
  }

  public fun update_direction(self: &mut Resource2, direction: Direction) {
    self.direction = direction
  }

  public fun get_table_id(): vector<u8> {
    table_id::encode(table_id::onchain_table_type(), TABLE_NAME)
  }

  public fun get_key_schemas(): vector<vector<u8>> {
    vector[]
  }

  public fun get_value_schemas(): vector<vector<u8>> {
    vector[b"address", b"u32", b"Direction"]
  }

  public fun get_key_names(): vector<vector<u8>> {
    vector[]
  }

  public fun get_value_names(): vector<vector<u8>> {
    vector[b"player", b"value", b"direction"]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let dapp_key = dapp_key::new();
    dapp_service::register_table(
            dapp_hub, 
            dapp_key,
            get_table_id(), 
            TABLE_NAME, 
            get_key_schemas(), 
            get_key_names(), 
            get_value_schemas(), 
            get_value_names(), 
            ctx
        );
  }

  public fun has(dapp_hub: &DappHub): bool {
    let key_tuple = vector::empty();
    dapp_service::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub) {
    let key_tuple = vector::empty();
    dapp_service::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_not_has(dapp_hub: &DappHub) {
    let key_tuple = vector::empty();
    dapp_service::ensure_not_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun has_player(dapp_hub: &DappHub): bool {
    let key_tuple = vector::empty();
    dapp_service::has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun ensure_has_player(dapp_hub: &DappHub) {
    let key_tuple = vector::empty();
    dapp_service::ensure_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun ensure_not_has_player(dapp_hub: &DappHub) {
    let key_tuple = vector::empty();
    dapp_service::ensure_not_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun has_value(dapp_hub: &DappHub): bool {
    let key_tuple = vector::empty();
    dapp_service::has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun ensure_has_value(dapp_hub: &DappHub) {
    let key_tuple = vector::empty();
    dapp_service::ensure_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun ensure_not_has_value(dapp_hub: &DappHub) {
    let key_tuple = vector::empty();
    dapp_service::ensure_not_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun has_direction(dapp_hub: &DappHub): bool {
    let key_tuple = vector::empty();
    dapp_service::has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 2)
  }

  public fun ensure_has_direction(dapp_hub: &DappHub) {
    let key_tuple = vector::empty();
    dapp_service::ensure_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 2)
  }

  public fun ensure_not_has_direction(dapp_hub: &DappHub) {
    let key_tuple = vector::empty();
    dapp_service::ensure_not_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 2)
  }

  public(package) fun delete(dapp_hub: &mut DappHub) {
    let key_tuple = vector::empty();
    dapp_service::delete_record<DappKey>(dapp_hub, dapp_key::new(), get_table_id(), key_tuple);
  }

  public fun get_player(dapp_hub: &DappHub): address {
    let key_tuple = vector::empty();
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0);
    let mut bsc_type = sui::bcs::new(value);
    let player = sui::bcs::peel_address(&mut bsc_type);
    player
  }

  public(package) fun set_player(dapp_hub: &mut DappHub, player: address) {
    let key_tuple = vector::empty();
    let value = to_bytes(&player);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 0, value);
  }

  public fun get_value(dapp_hub: &DappHub): u32 {
    let key_tuple = vector::empty();
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1);
    let mut bsc_type = sui::bcs::new(value);
    let value = sui::bcs::peel_u32(&mut bsc_type);
    value
  }

  public(package) fun set_value(dapp_hub: &mut DappHub, value: u32) {
    let key_tuple = vector::empty();
    let value = to_bytes(&value);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 1, value);
  }

  public fun get_direction(dapp_hub: &DappHub): Direction {
    let key_tuple = vector::empty();
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 2);
    let mut bsc_type = sui::bcs::new(value);
    let direction = example::direction::decode(&mut bsc_type);
    direction
  }

  public(package) fun set_direction(dapp_hub: &mut DappHub, direction: Direction) {
    let key_tuple = vector::empty();
    let value = example::direction::encode(direction);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 2, value);
  }

  public fun get(dapp_hub: &DappHub): (address, u32, Direction) {
    let key_tuple = vector::empty();
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    let mut bsc_type = sui::bcs::new(value_tuple);
    let player = sui::bcs::peel_address(&mut bsc_type);
    let value = sui::bcs::peel_u32(&mut bsc_type);
    let direction = example::direction::decode(&mut bsc_type);
    (player, value, direction)
  }

  public(package) fun set(dapp_hub: &mut DappHub, player: address, value: u32, direction: Direction) {
    let key_tuple = vector::empty();
    let value_tuple = encode(player, value, direction);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun get_struct(dapp_hub: &DappHub): Resource2 {
    let key_tuple = vector::empty();
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    decode(value_tuple)
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, resource2: Resource2) {
    let key_tuple = vector::empty();
    let value_tuple = encode_struct(resource2);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun encode(player: address, value: u32, direction: Direction): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&player));
    value_tuple.push_back(to_bytes(&value));
    value_tuple.push_back(example::direction::encode(direction));
    value_tuple
  }

  public fun encode_struct(resource2: Resource2): vector<vector<u8>> {
    encode(resource2.player, resource2.value, resource2.direction)
  }

  public fun decode(data: vector<u8>): Resource2 {
    let mut bsc_type = sui::bcs::new(data);
    let player = sui::bcs::peel_address(&mut bsc_type);
    let value = sui::bcs::peel_u32(&mut bsc_type);
    let direction = example::direction::decode(&mut bsc_type);
    Resource2 {
            player,
            value,
            direction,
        }
  }
}
