  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::resource8 {

  use sui::bcs::{to_bytes};

  use std::ascii::{string, String, into_bytes};

  use dubhe::table_id;

  use dubhe::dapp_service::{Self, DappHub};

  use dubhe::dapp_system;

  use example::dapp_key;

  use example::dapp_key::DappKey;

  const TABLE_NAME: vector<u8> = b"resource8";

  public struct Resource8 has copy, drop, store {
    player: address,
    name: String,
  }

  public fun new(player: address, name: String): Resource8 {
    Resource8 {
            player,
            name,
        }
  }

  public fun player(self: &Resource8): address {
    self.player
  }

  public fun name(self: &Resource8): String {
    self.name
  }

  public fun update_player(self: &mut Resource8, player: address) {
    self.player = player
  }

  public fun update_name(self: &mut Resource8, name: String) {
    self.name = name
  }

  public fun get_table_id(): vector<u8> {
    table_id::encode(table_id::onchain_table_type(), TABLE_NAME)
  }

  public fun get_key_schemas(): vector<vector<u8>> {
    vector[]
  }

  public fun get_value_schemas(): vector<vector<u8>> {
    vector[b"address", b"String"]
  }

  public fun get_key_names(): vector<vector<u8>> {
    vector[]
  }

  public fun get_value_names(): vector<vector<u8>> {
    vector[b"player", b"name"]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let dapp_key = dapp_key::new();
    dapp_system::register_table(
            dapp_hub, 
            dapp_key,
            get_table_id(), 
            get_key_schemas(), 
            get_key_names(), 
            get_value_schemas(), 
            get_value_names(), 
            ctx
        );
  }

  public fun has(dapp_hub: &DappHub): bool {
    let key_tuple = vector::empty();
    dapp_system::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub) {
    let key_tuple = vector::empty();
    dapp_system::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_not_has(dapp_hub: &DappHub) {
    let key_tuple = vector::empty();
    dapp_system::ensure_not_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public(package) fun delete(dapp_hub: &mut DappHub) {
    let key_tuple = vector::empty();
    dapp_system::delete_record<DappKey>(dapp_hub, dapp_key::new(), get_table_id(), key_tuple);
  }

  public fun get_player(dapp_hub: &DappHub): address {
    let key_tuple = vector::empty();
    let value = dapp_system::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0);
    let mut bsc_type = sui::bcs::new(value);
    let player = sui::bcs::peel_address(&mut bsc_type);
    player
  }

  public(package) fun set_player(dapp_hub: &mut DappHub, player: address) {
    let key_tuple = vector::empty();
    let value = to_bytes(&player);
    dapp_system::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 0, value);
  }

  public fun get_name(dapp_hub: &DappHub): String {
    let key_tuple = vector::empty();
    let value = dapp_system::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1);
    let mut bsc_type = sui::bcs::new(value);
    let name = string(sui::bcs::peel_vec_u8(&mut bsc_type));
    name
  }

  public(package) fun set_name(dapp_hub: &mut DappHub, name: String) {
    let key_tuple = vector::empty();
    let value = to_bytes(&into_bytes(name));
    dapp_system::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 1, value);
  }

  public fun get(dapp_hub: &DappHub): (address, String) {
    let key_tuple = vector::empty();
    let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    let mut bsc_type = sui::bcs::new(value_tuple);
    let player = sui::bcs::peel_address(&mut bsc_type);
    let name = string(sui::bcs::peel_vec_u8(&mut bsc_type));
    (player, name)
  }

  public(package) fun set(dapp_hub: &mut DappHub, player: address, name: String) {
    let key_tuple = vector::empty();
    let value_tuple = encode(player, name);
    dapp_system::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun get_struct(dapp_hub: &DappHub): Resource8 {
    let key_tuple = vector::empty();
    let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    decode(value_tuple)
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, resource8: Resource8) {
    let key_tuple = vector::empty();
    let value_tuple = encode_struct(resource8);
    dapp_system::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun encode(player: address, name: String): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&player));
    value_tuple.push_back(to_bytes(&into_bytes(name)));
    value_tuple
  }

  public fun encode_struct(resource8: Resource8): vector<vector<u8>> {
    encode(resource8.player, resource8.name)
  }

  public fun decode(data: vector<u8>): Resource8 {
    let mut bsc_type = sui::bcs::new(data);
    let player = sui::bcs::peel_address(&mut bsc_type);
    let name = string(sui::bcs::peel_vec_u8(&mut bsc_type));
    Resource8 {
            player,
            name,
        }
  }
}
