  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::dubhe_deploy_hook {

  use dubhe::dapp_hub::DappHub;
  use dubhe::dubhe_config;
  use dubhe::dubhe_wrapper_system;
  use sui::sui::SUI;
  use dubhe::dubhe::DUBHE;
  use dubhe::dubhe_dapp_key;

  public(package) fun run(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let next_asset_id = 0;
      // 0.3% swap fee
    let swap_fee = 30;
    let fee_to = ctx.sender();
    let max_swap_path_len = 6;
    dubhe_config::set(
      dapp_hub, 
      next_asset_id, 
      swap_fee, 
      fee_to, 
      max_swap_path_len
    );

    let sui_asset_id = dubhe_wrapper_system::do_register<SUI>(
      dapp_hub,
      b"Wrapped SUI",
      b"wSUI",
      b"Wrapped SUI",
    9,
    b"https://cryptologos.cc/logos/sui-sui-logo.png?v=040",
    );
    let dubhe_asset_id = dubhe_wrapper_system::do_register<DUBHE>(
      dapp_hub,
      b"Wrapped DUBHE",
      b"wDUBHE",
      b"Wrapped DUBHE",
      7,
      b"https://raw.githubusercontent.com/0xobelisk/dubhe/refs/heads/main/assets/logo.jpg",
    );

    std::debug::print(&sui_asset_id);
    std::debug::print(&dubhe_asset_id);
    
  }
}
