  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::bridge_config {

  use sui::bcs::{to_bytes};

  use std::ascii::{string, String, into_bytes};

  use dubhe::table_id;

  use dubhe::dapp_service::{Self, DappHub};

  use dubhe::dapp_system;

  use dubhe::dapp_key;

  use dubhe::dapp_key::DappKey;

  const TABLE_NAME: vector<u8> = b"bridge_config";

  const TABLE_TYPE: vector<u8> = b"Resource";

  const OFFCHAIN: bool = false;

  public struct BridgeConfig has copy, drop, store {
    min_amount: u256,
    fee: u256,
    opened: bool,
  }

  public fun new(min_amount: u256, fee: u256, opened: bool): BridgeConfig {
    BridgeConfig {
            min_amount,
            fee,
            opened,
        }
  }

  public fun min_amount(self: &BridgeConfig): u256 {
    self.min_amount
  }

  public fun fee(self: &BridgeConfig): u256 {
    self.fee
  }

  public fun opened(self: &BridgeConfig): bool {
    self.opened
  }

  public fun update_min_amount(self: &mut BridgeConfig, min_amount: u256) {
    self.min_amount = min_amount
  }

  public fun update_fee(self: &mut BridgeConfig, fee: u256) {
    self.fee = fee
  }

  public fun update_opened(self: &mut BridgeConfig, opened: bool) {
    self.opened = opened
  }

  public fun get_table_id(): String {
    string(TABLE_NAME)
  }

  public fun get_key_schemas(): vector<String> {
    vector[
    string(b"String")
    ]
  }

  public fun get_value_schemas(): vector<String> {
    vector[string(b"u256"), string(b"u256"),
    string(b"bool")
    ]
  }

  public fun get_key_names(): vector<String> {
    vector[
    string(b"chain")
    ]
  }

  public fun get_value_names(): vector<String> {
    vector[string(b"min_amount"), string(b"fee"),
    string(b"opened")
    ]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let dapp_key = dapp_key::new();
    dapp_service::register_table(
            dapp_hub,
             dapp_key,
            string(TABLE_TYPE),
            get_table_id(), 
            get_key_schemas(), 
            get_key_names(), 
            get_value_schemas(), 
            get_value_names(), 
            OFFCHAIN,
            ctx
        );
  }

  public fun has(dapp_hub: &DappHub, chain: String): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    dapp_service::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub, chain: String) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    dapp_service::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_not_has(dapp_hub: &DappHub, chain: String) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    dapp_service::ensure_not_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public(package) fun delete(dapp_hub: &mut DappHub, chain: String) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    dapp_service::delete_record<DappKey>(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, OFFCHAIN);
  }

  public fun get_min_amount(dapp_hub: &DappHub, chain: String): u256 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0);
    let mut bsc_type = sui::bcs::new(value);
    let min_amount = sui::bcs::peel_u256(&mut bsc_type);
    min_amount
  }

  public(package) fun set_min_amount(dapp_hub: &mut DappHub, chain: String, min_amount: u256) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    let value = to_bytes(&min_amount);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 0, value, OFFCHAIN);
  }

  public fun get_fee(dapp_hub: &DappHub, chain: String): u256 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1);
    let mut bsc_type = sui::bcs::new(value);
    let fee = sui::bcs::peel_u256(&mut bsc_type);
    fee
  }

  public(package) fun set_fee(dapp_hub: &mut DappHub, chain: String, fee: u256) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    let value = to_bytes(&fee);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 1, value, OFFCHAIN);
  }

  public fun get_opened(dapp_hub: &DappHub, chain: String): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 2);
    let mut bsc_type = sui::bcs::new(value);
    let opened = sui::bcs::peel_bool(&mut bsc_type);
    opened
  }

  public(package) fun set_opened(dapp_hub: &mut DappHub, chain: String, opened: bool) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    let value = to_bytes(&opened);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 2, value, OFFCHAIN);
  }

  public fun get(dapp_hub: &DappHub, chain: String): (u256, u256, bool) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    let mut bsc_type = sui::bcs::new(value_tuple);
    let min_amount = sui::bcs::peel_u256(&mut bsc_type);
    let fee = sui::bcs::peel_u256(&mut bsc_type);
    let opened = sui::bcs::peel_bool(&mut bsc_type);
    (min_amount, fee, opened)
  }

  public(package) fun set(dapp_hub: &mut DappHub, chain: String, min_amount: u256, fee: u256, opened: bool) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    let value_tuple = encode(min_amount, fee, opened);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public fun get_struct(dapp_hub: &DappHub, chain: String): BridgeConfig {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    decode(value_tuple)
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, chain: String, bridge_config: BridgeConfig) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&chain));
    let value_tuple = encode_struct(bridge_config);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public fun encode(min_amount: u256, fee: u256, opened: bool): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&min_amount));
    value_tuple.push_back(to_bytes(&fee));
    value_tuple.push_back(to_bytes(&opened));
    value_tuple
  }

  public fun encode_struct(bridge_config: BridgeConfig): vector<vector<u8>> {
    encode(bridge_config.min_amount, bridge_config.fee, bridge_config.opened)
  }

  public fun decode(data: vector<u8>): BridgeConfig {
    let mut bsc_type = sui::bcs::new(data);
    let min_amount = sui::bcs::peel_u256(&mut bsc_type);
    let fee = sui::bcs::peel_u256(&mut bsc_type);
    let opened = sui::bcs::peel_bool(&mut bsc_type);
    BridgeConfig {
            min_amount,
            fee,
            opened,
        }
  }
}
