  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module test_project::position2 {

  use sui::bcs::{to_bytes};

  use dubhe::table_id;

  use dubhe::dapp_state;

  use dubhe::dapp_service;

  use dubhe::dapp_hub;

  use dubhe::dapp_hub::DappHub;

  use test_project::dapp_key;

  use test_project::dapp_key::DappKey;

  use test_project::direction;

  use test_project::direction::{Direction};

  const TABLE_NAME: vector<u8> = b"position2";

  public struct Position2 has copy, drop, store {
    x: u64,
    y: u64,
    direction: Direction,
  }

  public fun new(x: u64, y: u64, direction: Direction): Position2 {
    Position2 {
            x,
            y,
            direction,
        }
  }

  public fun x(self: &Position2): u64 {
    self.x
  }

  public fun y(self: &Position2): u64 {
    self.y
  }

  public fun direction(self: &Position2): Direction {
    self.direction
  }

  public fun update_x(self: &mut Position2, x: u64) {
    self.x = x
  }

  public fun update_y(self: &mut Position2, y: u64) {
    self.y = y
  }

  public fun update_direction(self: &mut Position2, direction: Direction) {
    self.direction = direction
  }

  public fun get_table_id(): vector<u8> {
    table_id::encode(table_id::onchain_table_type(), TABLE_NAME)
  }

  public fun get_key_schemas(): vector<vector<u8>> {
    vector[b"address"]
  }

  public fun get_value_schemas(): vector<vector<u8>> {
    vector[b"u64", b"u64", b"Direction"]
  }

  public fun get_key_names(): vector<vector<u8>> {
    vector[b"entity_id"]
  }

  public fun get_value_names(): vector<vector<u8>> {
    vector[b"x", b"y", b"direction"]
  }

  public fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let dapp_key = dapp_key::new();
    dapp_service::register_table(
            dapp_hub, 
            dapp_key,
            get_table_id(), 
            TABLE_NAME, 
            get_key_schemas(), 
            get_key_names(), 
            get_value_schemas(), 
            get_value_names(), 
            ctx
        );
  }

  public fun has(dapp_hub: &DappHub, entity_id: address): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub, entity_id: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_not_has(dapp_hub: &DappHub, entity_id: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::ensure_not_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun has_x(dapp_hub: &DappHub, entity_id: address): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun ensure_has_x(dapp_hub: &DappHub, entity_id: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::ensure_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun ensure_not_has_x(dapp_hub: &DappHub, entity_id: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::ensure_not_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0)
  }

  public fun has_y(dapp_hub: &DappHub, entity_id: address): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun ensure_has_y(dapp_hub: &DappHub, entity_id: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::ensure_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun ensure_not_has_y(dapp_hub: &DappHub, entity_id: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::ensure_not_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1)
  }

  public fun has_direction(dapp_hub: &DappHub, entity_id: address): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 2)
  }

  public fun ensure_has_direction(dapp_hub: &DappHub, entity_id: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::ensure_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 2)
  }

  public fun ensure_not_has_direction(dapp_hub: &DappHub, entity_id: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::ensure_not_has_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 2)
  }

  public fun delete(dapp_hub: &mut DappHub, entity_id: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    dapp_service::delete_record<DappKey>(dapp_hub, dapp_key::new(), get_table_id(), key_tuple);
  }

  public fun get_x(dapp_hub: &DappHub, entity_id: address): u64 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 0);
    let mut bsc_type = sui::bcs::new(value);
    let x = sui::bcs::peel_u64(&mut bsc_type);
    x
  }

  public fun set_x(dapp_hub: &mut DappHub, entity_id: address, x: u64) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    let value = to_bytes(&x);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 0, value);
  }

  public fun get_y(dapp_hub: &DappHub, entity_id: address): u64 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 1);
    let mut bsc_type = sui::bcs::new(value);
    let y = sui::bcs::peel_u64(&mut bsc_type);
    y
  }

  public fun set_y(dapp_hub: &mut DappHub, entity_id: address, y: u64) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    let value = to_bytes(&y);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 1, value);
  }

  public fun get_direction(dapp_hub: &DappHub, entity_id: address): Direction {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    let value = dapp_service::get_field<DappKey>(dapp_hub, get_table_id(), key_tuple, 2);
    let mut bsc_type = sui::bcs::new(value);
    let direction = test_project::direction::decode(&mut bsc_type);
    direction
  }

  public fun set_direction(dapp_hub: &mut DappHub, entity_id: address, direction: Direction) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    let value = test_project::direction::encode(direction);
    dapp_service::set_field(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, 2, value);
  }

  public fun get(dapp_hub: &DappHub, entity_id: address): (u64, u64, Direction) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    let mut bsc_type = sui::bcs::new(value_tuple);
    let x = sui::bcs::peel_u64(&mut bsc_type);
    let y = sui::bcs::peel_u64(&mut bsc_type);
    let direction = test_project::direction::decode(&mut bsc_type);
    (x, y, direction)
  }

  public fun set(dapp_hub: &mut DappHub, entity_id: address, x: u64, y: u64, direction: Direction) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    let value_tuple = encode(x, y, direction);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun get_struct(dapp_hub: &DappHub, entity_id: address): Position2 {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    let value_tuple = dapp_service::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    decode(value_tuple)
  }

  public fun set_struct(dapp_hub: &mut DappHub, entity_id: address, position2: Position2) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&entity_id));
    let value_tuple = encode_struct(position2);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple);
  }

  public fun encode(x: u64, y: u64, direction: Direction): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&x));
    value_tuple.push_back(to_bytes(&y));
    value_tuple.push_back(test_project::direction::encode(direction));
    value_tuple
  }

  public fun encode_struct(position2: Position2): vector<vector<u8>> {
    encode(position2.x, position2.y, position2.direction)
  }

  public fun decode(data: vector<u8>): Position2 {
    let mut bsc_type = sui::bcs::new(data);
    let x = sui::bcs::peel_u64(&mut bsc_type);
    let y = sui::bcs::peel_u64(&mut bsc_type);
    let direction = test_project::direction::decode(&mut bsc_type);
    Position2 {
            x,
            y,
            direction,
        }
  }
}
